name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
  push:
    branches-ignore:
      - 'main'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.0, 8.1, 8.2]

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
          args: --ignore-platform-reqs
      - name: PHPUnit Unit Tests
        uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml.dist
          php_version: ${{ matrix.php-version }}
          php_extensions: bcmath gmp xdebug
          testsuite: Unit
          version: 9

  integration-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ 8.0, 8.1, 8.2 ]

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
          args: --ignore-platform-reqs
      - name: Prepare DB
        run: |
          php bin/console doctrine:database:create
          php bin/console doctrine:schema:update --force --env=test
      - name: PHPUnit Integration Tests
        uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml.dist
          php_version: ${{ matrix.php-version }}
          php_extensions: bcmath gmp xdebug
          testsuite: Integration
          version: 9

  phpcs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ 8.0, 8.1, 8.2 ]

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
          php_extensions: bcmath gmp xdebug
      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --standard=phpcs.xml.dist
